<?php
$validated_identity = $block->getIdentityValid(false);
if($validated_identity->valid) {
    echo 'Identity is received and valid. Thanks!';
    
} else {
    echo $validated_identity->invalid_message;
    // echo "<hr>";
    //     echo 'Identity is not yet validated or not valid.';
    $url = $block->getBaseUrl()."bluem/identity/request";
    echo "<p class='bluem-p'>
    <a href='$url' target='_blank' class='bluem-button button action primary'>
    You can validate your identity here
    </a>
    </p>";
}
// var_dump($validated_identity->age_data);