<?php
// echo "<h2>Identificeren met iDIN via je vertrouwde bank is veilig en snel<h2>";
// echo "<p>net zoals iDeal. Het duurt hoogstens één minuut en het resultaat wordt opgeslagen voor vervolgtransacties als je ingelogd bent als reguliere klant.</p>"; 

echo "<h2 class='bluem-h2'>Identifying with iDIN using your trusted bank is safe and fast</h2>";
echo "<p class='bluem-p'>";
echo $block->getAdditionalIdinInfo();
echo "</p>";
echo "<p class='bluem-p'>
<a href='https://www.idin.nl/en/consumers/' target='_self' class='bluem-button'>Read more about iDIN here</a> or simply close this window.
</p>";
echo "<br>";