<?php

if ($block->getUserLoggedIn())
{
    $identified = $block->getIdentityValid();

    if ($block->debugMode()) {
        var_dump($identified);
    }

    if (!empty($identified->valid)) {
        if (!empty($identified->report)) {
            echo "<p>You have verified your identity on " . \Carbon\Carbon::parse($identified->report->DateTime)->format('Y-m-d') . " at " . \Carbon\Carbon::parse($identified->report->DateTime)->format('H:i') . ". Thank you.</p>";
        } else {
            echo "<p>Your identity has been verifed. Thank you.</p>";
        }
        //echo "<p>If you want, you can do it again.</p>";
        //echo $block->showBluemIdentityButton();
        /*
        echo "<br><pre>";
        var_dump($identified->report);
        echo "</pre>";
        */
    } else {
        echo "<p>Identity not verfied yet.</p><br>";
            
        echo $block->showBluemIdentityButton();
        echo "<br><small><a href='".$block->getBaseUrl()."bluem/identity/information' target='_blank'>What is this?</a></small>";
    }
    
    if ($block->debugMode()) {
        echo "<hr>User data:<br><pre>";
        var_dump($block->getUserData());
        echo "</pre>";
    }
} else {
    echo "<p>You need to log in before you can peruse the Identification procedure.</p>";
}
