<p>
Here you can see all the important data surrounding ePayments (iDeal). 
Also make sure the module is configured properly.
<p>
Refer to the readme at module for detailed instructions. If you have any questions or problems, contact the primary developer at <a 
href="mailto:d.rijpkema@bluem.nl?subject=Magento" target="_blank">d.rijpkema@bluem.nl</a>.</p>
<br>

<h3>
Payment Requests Overview
</h3>
<p>Below you see the details of all payments performed so far. 
The Payload column contains more information about the request.
</p>
<?php
echo $block->getRequestsTableHTML('payment');
?>  
