<?php
/* Based on  php-cuong/magento-offline-payments  */
/**
 * @var $block \Bluem\Integration\Block\Form\EPayment
 */
$methodCode = $block->escapeHtml($block->getMethodCode());
?>
<fieldset class="fieldset items <?= /* @noEscape */ $methodCode ?>" id="payment_form_<?= /* @noEscape */ $methodCode ?>">
    <div class="field number required">
        <label for="issuer" class="label"><span><?= $block->escapeHtml(__('Selecteer een bank')) ?></span></label>
        <div class="control">
            <select id="issuer" name="payment[additional_data][issuer]" class="input-select">
                <option value="RABO">Rabobank (test)</option>
                <option value="INGB">ING Bank (test)</option>
            </select>
        </div>
    </div>
</fieldset>
